services:
  - type: web
    name: medflect-backend
    env: node
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_ORIGIN
        # Set this after Vercel deploy to your frontend URL (comma-separated if multiple)
        value: ""
    healthCheckPath: /api/health
